# Image hashes in this file are for amd64 systems
# NB: May include paths relative to the "server/build" directory, which contains the original compose file that this yaml is overriding

version: "2.4"
services:
  server:
    image: ${SERVER_IMAGE}
    restart: always
    env_file:
      - "./.env.server"
    environment:
      MM_LICENSE: ${MM_LICENSE}
      MM_SERVICESETTINGS_SITEURL: http://server:8065
      MM_SERVICESETTINGS_ENABLELOCALMODE: "true"
      MM_PLUGINSETTINGS_ENABLED: "true"
      MM_PLUGINSETTINGS_ENABLEUPLOADS: "true"
      MM_PLUGINSETTINGS_AUTOMATICPREPACKAGEDPLUGINS: "true"
      MM_TEAMSETTINGS_ENABLEOPENSERVER: "true"
      MM_SQLSETTINGS_DATASOURCE: "postgres://mmuser:mostest@postgres:5432/mattermost_test?sslmode=disable&connect_timeout=10&binary_parameters=yes"
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_EMAILSETTINGS_SMTPSERVER: inbucket
      MM_CLUSTERSETTINGS_READONLYCONFIG: "false"
      MM_SERVICESETTINGS_ENABLEONBOARDINGFLOW: "false"
      MM_FEATUREFLAGS_ONBOARDINGTOURTIPS: "false"
      MM_SERVICEENVIRONMENT: test
    ports:
      - "8065:8065"
    depends_on:
      postgres:
        condition: service_healthy
      inbucket:
        condition: service_healthy

  postgres:
    image: mattermostdevelopment/mirrored-postgres:12
    restart: always
    environment:
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: mostest
      POSTGRES_DB: mattermost_test
    command: postgres -c "config_file=/etc/postgresql/postgresql.conf"
    volumes:
      - "../../server/build/docker/postgres.conf:/etc/postgresql/postgresql.conf"
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost"]
      interval: 10s
      timeout: 15s
      retries: 12
    networks:
      default:
        aliases:
          - postgres

  inbucket:
    restart: "no"
    container_name: mattermost-inbucket
    ports:
      - "9001:9001"
      - "10025:10025"
      - "10110:10110"
    extends:
      file: ../../server/build/gitlab-dc.common.yml
      service: inbucket

  start_dependencies:
    image: mattermost/mattermost-wait-for-dep:latest
    depends_on:
      - postgres
      - inbucket
    command: postgres:5432 inbucket:9001
    networks:
      default:

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
    external: true
