site_name: Mattermost Documentation
site_url: http://docs.mattermost.org
repo_url: https://github.com/mattermost/platform
repo_name: GitHub
site_favicon: favicon.ico
copyright: "Copyright (c) 2015 Mattermost, Inc. All Rights Reserved."
strict: true
docs_dir: doc
site_dir: documentation-html
use_directory_urls: false
theme: mkdocs
