version: '2.4'
services:
  mysql:
    restart: 'no'
    container_name: mattermost-mysql
    ports:
      - "3306:3306"
    extends:
        file: build/docker-compose.common.yml
        service: mysql
  mysql-read-replica:
    restart: 'no'
    container_name: mattermost-mysql-read-replica
    ports:
      - "3307:3306"
    extends:
        file: build/docker-compose.common.yml
        service: mysql-read-replica
  postgres:
    restart: 'no'
    container_name: mattermost-postgres
    ports:
      - "5432:5432"
    extends:
        file: build/docker-compose.common.yml
        service: postgres
  minio:
    restart: 'no'
    container_name: mattermost-minio
    ports:
      - "9000:9000"
    extends:
        file: build/docker-compose.common.yml
        service: minio
  inbucket:
    restart: 'no'
    container_name: mattermost-inbucket
    ports:
      - "9001:9001"
      - "10025:10025"
      - "10110:10110"
    extends:
        file: build/docker-compose.common.yml
        service: inbucket
  openldap:
    restart: 'no'
    container_name: mattermost-openldap
    ports:
      - "389:389"
      - "636:636"
    extends:
        file: build/docker-compose.common.yml
        service: openldap
  elasticsearch:
    restart: 'no'
    container_name: mattermost-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    extends:
        file: build/docker-compose.common.yml
        service: elasticsearch
  dejavu:
    restart: 'no'
    container_name: mattermost-dejavu
    ports:
      - "1358:1358"
    extends:
        file: build/docker-compose.common.yml
        service: dejavu
  keycloak:
    restart: 'no'
    container_name: mattermost-saml
    ports:
      - "8484:8080"
    extends:
        file: build/docker-compose.common.yml
        service: keycloak
  prometheus:
    restart: 'no'
    container_name: mattermost-prometheus
    ports:
      - "9090:9090"
    extends:
        file: build/docker-compose.common.yml
        service: prometheus
  grafana:
    restart: 'no'
    container_name: mattermost-grafana
    ports:
      - "3000:3000"
    extends:
        file: build/docker-compose.common.yml
        service: grafana

networks:
  mm-test:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.254.0/24
          ip_range: 192.168.254.0/24
