name: Opensearch Docker Image

on:
  push:
    branches:
      - master
    paths:
      - server/build/Dockerfile.opensearch
      - .github/workflows/build-opensearch-image.yml

jobs:
  build-image:
    runs-on: ubuntu-22.04
    steps:
      - name: opensearch/checkout-repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: opensearch/docker-login
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          username: ${{ secrets.DOCKERHUB_DEV_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEV_TOKEN }}

      - name: opensearch/build-and-push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          provenance: false
          file: server/build/Dockerfile.opensearch
          push: true
          pull: true
          tags: mattermostdevelopment/mattermost-opensearch:2.7.0
          build-args: |
            OPENSEARCH_VERSION=2.7.0
