---
name: Push mirrored docker images
on:
  push:
    branches:
      - master
    paths:
      - server/scripts/mirror-docker-images.*

jobs:
  build-docker:
    name: cd/Push mirrored docker images
    if: github.repository_owner == 'mattermost'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout mattermost project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: cd/Login to Docker Hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          username: ${{ secrets.DOCKERHUB_DEV_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEV_TOKEN }}
      - name: cd/Run image upload script
        env:
          IMAGES_FILE: server/scripts/mirror-docker-images.json
          DRY_RUN: no
        run: ./server/scripts/mirror-docker-images.sh
