---
# Temporary test workflow â€” DELETE before merging PR #35205
name: "[A2] E2E Tests (on merge - release)"
on:
  push:
    branches:
      - SEC-9513

jobs:
  test-on-merge-release:
    uses: ./.github/workflows/e2e-tests-on-merge.yml
    with:
      branch: release-11.4
      commit_sha: 892849727d7b0a2706ceae419a8696dcc60b8780
      server_image_tag: 8928497_bef17b6
    secrets: inherit
