---
# Temporary test workflow â€” DELETE before merging PR #35205
name: "[A3] E2E Tests (on release)"
on:
  push:
    branches:
      - SEC-9513

jobs:
  test-on-release:
    uses: ./.github/workflows/e2e-tests-on-release.yml
    with:
      branch: release-11.4
      commit_sha: 33052a19e49b04f1c221992787ae76e266578e17
      server_image_tag: "11.4.0-rc2"
      server_image_aliases: ""
    secrets: inherit
