---
# Temporary test workflow â€” DELETE before merging PR #35205
name: "[A1] E2E Tests (on merge - master)"
on:
  push:
    branches:
      - SEC-9513

jobs:
  test-on-merge-master:
    uses: ./.github/workflows/e2e-tests-on-merge.yml
    with:
      branch: master
      commit_sha: 2bd29c03593643821144d59ae57725c30db7a07a
      server_image_tag: 2bd29c0_6111752
    secrets: inherit
